version: "3.8"
services:
  php:
    image: "docker.io/composer:latest"
    container_name: "php-laravel"
    restart: unless-stopped
    environment:
      - PORT=8080
    command: ./entrypoint.sh
    volumes:
      - type: bind
        source: "."
        target: "/app"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080", "-f", "-o", "/dev/null"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 40s
      start_interval: 5s
  nginx:
    image: "docker.io/nginx:mainline" # using bookworm edition so openssl is available by default
    container_name: "nginx-php-proxy"
    attach: false
    restart: unless-stopped
    read_only: true
    command: ./scripts/entrypoint.sh
    environment:
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
    depends_on:
      php:
        condition: service_started
        restart: false
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - backend
    volumes:
      # Allow for better generation of certificates
      - type: bind
        source: "/dev/random"
        target: "/dev/random"
        read_only: true
      - type: bind
        source: "/dev/urandom"
        target: "/dev/urandom"
        read_only: true
      - type: bind
        source: "nginx/templates"
        target: "/etc/nginx/templates"
        read_only: true
      - type: bind
        source: "nginx/conf.d"
        target: "/etc/nginx/conf.d"
        read_only: false
          # must be writable. For nginx template engine to populate configs from template folder. 
          # https://hub.docker.com/_/nginx
      - type: bind
        source: "nginx/scripts"
        target: "/etc/nginx/scripts"
        read_only: true
      - type: volume
        source: nginx-ssl
        target: "/etc/nginx/ssl"
      - type: volume
        source: nginx-cache
        target: "/var/cache/nginx"
      - type: volume
        source: nginx-pid
        target: "/var/run"
    working_dir: "/etc/nginx/"
volumes:
  nginx-cache:
  nginx-pid:
  nginx-ssl:
networks:
  backend:
