version: "3.8"
services:
  php:
    image: "docker.io/composer:latest"
    container_name: "php-laravel"
    restart: unless-stopped
    environment:
      - PORT=8080
    command: ./entrypoint.sh
    volumes:
      - type: bind
        source: "."
        target: "/app"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080", "-f", "-o", "/dev/null"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 40s
      start_interval: 5s
    depends_on:
      postgres:
        condition: service_started
        restart: false
  postgres:
    image: "docker.io/postgres:16-alpine"
    container_name: "postgres-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - type: volume
        source: db-data
        target: "/var/lib/postgresql/data"
    networks:
      - backend
  nginx:
    image: "docker.io/nginx:mainline" # using bookworm edition so openssl is available by default
    container_name: "nginx-php-proxy"
    attach: false
    restart: unless-stopped
    read_only: true
    command: ./scripts/entrypoint.sh
    environment:
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
    depends_on:
      php:
        condition: service_started
        restart: false
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - backend
    volumes:
      # Allow for better generation of certificates
      - type: bind
        source: "/dev/random"
        target: "/dev/random"
        read_only: true
      - type: bind
        source: "/dev/urandom"
        target: "/dev/urandom"
        read_only: true
      - type: bind
        source: "nginx/templates"
        target: "/etc/nginx/templates"
        read_only: true
      - type: tmpfs
        target: "/etc/nginx/conf.d"
        tmpfs:
            size: "12k"
      - type: bind
        source: "nginx/scripts"
        target: "/etc/nginx/scripts"
        read_only: true
      - type: tmpfs
        target: "/etc/nginx/ssl"
        tmpfs:
            size: "8k"
      - type: volume
        source: nginx-cache
        target: "/var/cache/nginx"
      - type: tmpfs
        target: "/var/run"
        tmpfs:
            size: "12k"
    working_dir: "/etc/nginx/"
volumes:
  nginx-cache:
  db-data:
networks:
  backend:
